AWSTemplateFormatVersion: '2010-09-09'
Description: 'Food App'

Resources:
  FoodUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      Schema:
        -
          Mutable: true
          Name: email
          Required: true

      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False

  WebClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties: 
      ClientName: FoodWeb
      GenerateSecret: False
      RefreshTokenValidity: 30
      UserPoolId: !Ref FoodUserPool
      CallbackURLs:
        - http://localhost:3000/      
      LogoutURLs:
        - http://localhost:3000/
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - phone
        - profile
        - aws.cognito.signin.user.admin
      SupportedIdentityProviders:
        - COGNITO
      
  ProcessClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties: 
      ClientName: FoodProcess
      GenerateSecret: True
      RefreshTokenValidity: 30
      UserPoolId: !Ref FoodUserPool
      SupportedIdentityProviders:
        - COGNITO
      

  FoodAPI:    
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${AWS::StackName}_API"
      Description: "Food API"

  APIDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      StageName: Dev
      RestApiId: !Ref FoodAPI   
    DependsOn:
      - "FoodAnyMethod"
  
  UserAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties: 
      AuthType: cognito_user_pools
      IdentitySource: method.request.header.Authorization
      Name: !Sub auth_${AWS::StackName}
      ProviderARNs:
        - !GetAtt FoodUserPool.Arn
      RestApiId:
        Ref: FoodAPI
      Type: COGNITO_USER_POOLS
  
  FoodResource:
    Type: AWS::ApiGateway::Resource
    Properties: 
      ParentId: !GetAtt 
        - FoodAPI
        - RootResourceId
      PathPart: food
      RestApiId: !Ref FoodAPI
  
  FoodAnyMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: COGNITO_USER_POOLS 
      AuthorizerId: 
        Ref: UserAuthorizer
      HttpMethod: "ANY"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt FoodLambda.Arn
      ResourceId: !Ref FoodResource     
      RestApiId: !Ref FoodAPI 

  FoodOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: FoodAPI
      ResourceId:
        Ref: FoodResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false 

  FoodPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "FoodLambda.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FoodAPI}/*/*/food"
  
  FoodLambda:
    Type: AWS::Lambda::Function
    Properties:      
      Code:
          ZipFile: |
            import random
            foods = ['dougnut', 'pizza', 'coffee', 'quinoa', 'sushi']

            def handler(event, context):
              food = foods[random.randrange(0, 5)]
              return {
                  'statusCode': 200,
                  'body': food,
                  'headers': {
                      'Content-Type': 'application/json',
                      'Access-Control-Allow-Origin': "*",
                  }
              }

            def list_foods(event, context):
              return {
                'statusCode': 200,
                'body': foods,
                'headers': {                    
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': "*",
                }
              }
      Description: "Food lambda"
      Handler: "index.handler"
      Role: !GetAtt FoodLambdaExecRole.Arn
      Runtime: python3.7
      Timeout: 20   

  FoodLambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
      Description: App Lambda execution policy
      Path: /
      Policies: 
        - 
          PolicyName: "FoodLambdaPolicies"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: 
                  - "logs:PutLogEvents"
                  - "logs:CreateLogStream"
                Resource: "*" # clean this up in all roles
              - 
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                Resource: "*"  

Outputs:
  appconfig:
    Description: The body
    Value: !Sub >
      {
        Auth: {
          region: 'us-west-2',
          userPoolId: '${FoodUserPool}',
          userPoolWebClientId: '${WebClient}'
        },
        API: {
            endpoints: [
                {
                    name: 'training',
                    endpoint: 'https://${FoodAPI}.execute-api.us-west-2.amazonaws.com/Dev/'
                }
            ]
        },
      }
  appclient:
    Description: client ID for the machine clinet
    Value: !Ref ProcessClient

# aws cloudformation create-stack --stack-name training --template-body file://Food.yaml --capabilities CAPABILITY_IAM

# aws cloudformation describe-stacks | jq -r '.Stacks []| select(.StackName == "training") | .Outputs[].OutputValue'